package group1.comp535.rice.indoorlocation.adapter;

import android.app.Activity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.TextView;

import java.util.List;

import group1.comp535.rice.indoorlocation.R;
import group1.comp535.rice.indoorlocation.data.WiFiData;

/**
 * Created by daiwei.ldw on 3/25/18.
 */

public class WiFiDataAdapter extends BaseAdapter {
    Activity context;
    List<WiFiData> wifidata;

    public WiFiDataAdapter(Activity context, List<WiFiData>wifiData){
        this.context = context;
        this.wifidata = wifiData;

    }

    @Override
    public int getCount() {
        // TODO Auto-generated method stub
        return this.wifidata.size();
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
//        Log.v("listview","drawing "+position);
        LayoutInflater inflater = context.getLayoutInflater();
        View view;

        if (convertView==null) {
            // get the view object generated by the inflate
            view = inflater.inflate(R.layout.wifi_list_info_item, null);
        }else{
            view=convertView;
        }
        TextView wifi_name = (TextView) view.findViewById(R.id.wifi_display_name);
        wifi_name.setText(wifidata.get(position).getName());

        TextView bssid = (TextView) view.findViewById(R.id.bssid);
        bssid.setText("BSSID: "+wifidata.get(position).getName());

        TextView strength = (TextView) view.findViewById(R.id.strength);
        strength.setText("Strength: "+wifidata.get(position).getStrength1()+" dBm / "+wifidata.get(position).getStrength2()+" dBm");

        return view;
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public Object getItem(int position) {
        return wifidata.get(position);
    }
}
